[package]
name = "manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-escape = "0.2.12"
nxml = "1.4.0"
thiserror = "1.0.38"
walkdir = "2.3.2"
